### ISSUE TITLE
Question: Any way to hide the /docs that is compatible with fastapi_msal?

### ISSUE THREAD

**Issue by jlerman44** [dudil/fastapi_msal#2]
Hello dudil,

I am trying to hide my documentation (so /docs, /redoc, and /openapi.json not accessible without msal login). Any idea how to achieve this?

I have tried a few things based on reading:

```
@app.get("/openapi.json", include_in_schema=False)
async def get_open_api_endpoint(current_user: str = Depends(get_current_user)):
    return JSONResponse(get_openapi(title="Kithara", version=0.1, routes=app.routes))

@app.get("/docs", include_in_schema=False)
async def get_documentation(current_user: str = Depends(get_current_user)):
    return get_swagger_ui_html(openapi_url="/openapi.json", title="docs")
```

and then initialize the fastapi app with

```
app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)
```

However, if this is done I do not think fastapi_msal can function. I get weird redirect related errors

In this example "get_current_user" was just using some simple APIKeyCookie stuff.
```
cookie_sec = APIKeyCookie(name="session")
secret_key = "zzzzzzzzzzzzzzzzzzzzzzz"
users = {"xxxxxxxxxxxxx": {"password": "yyyyyyyyyyyyyyyyyyyyy"}}

# for login to docs
def get_current_user(session: str = Depends(cookie_sec)):
    try:
        payload = jwt.decode(session, secret_key)
        user = users[payload["sub"]]
        return user
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN, detail="Invalid authentication"
        )
```

***Though ideally this would be Microsoft based login.***

Any ideas how I can achieve this?

**Comment by dudil** [comment]
Hi @jlerman44,

about this
> I am trying to hide my documentation (so /docs, /redoc, and /openapi.json not accessible without msal login)

I'm not sure you can have a conditional documentation so only who is already authenticated can see them.
I will add that while the documentation feature in _fastapi_ is amazing, it has its downsides and it is quite a headache to "hack" it. So I suggest either show it or hide.

If you wish to switch only the _fastapi_msal_ parts this could be done via the configuration class __MSALClientConfig__
In the example provide you can set:
```python
client_config: MSALClientConfig = MSALClientConfig()
client_config.show_in_docs = False  # False currently is default
# you can also set your own customized routing paths
client_config.login_path = ...   # This is the initial path to start the login process (should be call by the application client)
client_config.token_path = ...   # This is the path that you provide to MS on the app registration process.
                                 # it will be used by MS as the token call-back
client_config.logout_path = ...  # This is the path the application client will use to logout the user
```

The docs are important only if you use them for the actual initialization process.
Indeed, if you will start with the docs the library will try to follow the already implemented OAuth2 path which is part of the open_api websites (hence the "strange" redirects you mentioned).
But if you are not going to use the docs at all - it won't be redirecting to them.


> Though ideally this would be Microsoft based login.

This could be achieved by the following adaptations to your code:
1. When you would like to show the client the login page - redirect to the login_path
    the default login path is "/_login_route"
1. The callback url is the one set on the client config class - default is "/token"
    Make sure to register "YOUR_URL/token" as part of the app registration process.

A short deep dive into the paths, router etc.
The router itself is implemented in the _MSALAuthorization_ class.
There are two different _token path_ classes:
GET operation method - this is useful if you wish to interact directly with the MS based login as mentioned.
Since MS callback is a GET call

POST operation method - this is useful if you use the documentation or any client which retrieve the token from MS and than forward the token to the API (This is the "offical" way of the OAuth2 flow - but I think it is not always correct to use it)

There are two different methods since they are also sourced from different places and holds different APIs.
To make the documentation and the MS direct approach work nice together I had to take this approach.

**Comment by jlerman44** [comment]
Thanks for these helpful pointers!  I will probably press on to try to find a way to hide the /docs behind a username and password while keeping fastapi_msal working. This is really important to me. If you have further ideas here, please let me know!  

Also, I think the redirect URL that is being used by default is YOUR_URL/docs/oauth2-redirect and not YOUR_URL/token. Is that strange?

**Comment by jlerman44** [comment]
OK.. best way is to solve in a different layer https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization   . I can confirm it works well.. at least for a SINGLE container app. (This feature is not available for multi container deployments yet, per the documentation as of today anwyays).

**Comment by jlerman44** [comment]
This also can be closed.

**Comment by dudil** [comment]
Hi @jlerman44,

The strange behavior is the mixture of using the FastAPI OpenAPI documentation website to simulate the login etc. vs how this should be used in production.
To be honest, you have a very solid point which is related to non exist documentation for this project. I only now realise it is quite a complex... 😬
Must admit I'm not expert in that field and if you can assist with setting up the basic of it that would be amazing!

BTW I've created my own private poc basedr to what MS created in this repository:
https://github.com/Azure-Samples/ms-identity-python-webapp
If you believe you can find it useful, please let me know and I'll be happy to clean it up and share it.
